# This is a basic workflow to help you get started with Actions

name: Metrics

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Metrics embed
      - uses: lowlighter/metrics@v3.32
        with:
          filename: metrics.svg
          base: header, activity, repositories
          token: ${{ secrets.METRICS_TOKEN }}
          user: AlbertAyy
          template: classic
          config_timezone: Asia/Chongqing

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          config_order: base.header, isocalendar

