# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Metrics embed
        # You may pin to the exact commit or the version.
        # uses: lowlighter/metrics@3dd06164327476b9730a815a70ad39cbf5032f7e
      - uses: lowlighter/metrics@v3.32
        with:
          # Base content
          base: header, activity, repositories
          # GitHub Personal Access Token
          token: ${{ secrets.METRICS_TOKEN }}
          # GitHub username
          user: AlbertAyy

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

